<?php 
class wudimei_view_default_index_comment_tags 
{
 public $__vars; 
 public $__view; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '
'; 
 
if( $role == 'admin'){  
 
 $__output .= '
hello,'; 
  $__r =$role;  $__output .=  htmlspecialchars($__r);  
 $__output .= '
'; 
 
 }else{   
 
 $__output .= '
hello,guest
'; 
 
 }  
 
 $__output .= '

'; 
 
if( !empty($years) ){foreach($years as $year){  
 
 $__output .= '
'; 
 
  $__r =$year;  $__output .=  htmlspecialchars($__r);  
 
 $__output .= '<br />
'; 
 
  }}else{{   
 
 $__output .= '
sorry,years arrary is empty
'; 
 
  }}   
 
 $__output .= '

'; 
if( count( $years) == 4 ){  
 $__output .= '
4 years
'; 
 }else{   
 $__output .= '
not 4 years
'; 
 }  
 $__output .= '

'; 
 
 $__output .= $this->body();  
 
 $__output .= '
'; 
 return $__output; 
} 
public function body(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 
 $__output .= '
this is the body
'; 
 
 return $__output; 
} 

}