<?php 
class wudimei_view_default_index_end 
{
 public $__vars; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '

'; 
if( $role == 'admin' ){  
 $__output .= '
	hello,admin
'; 
 }else{   
 $__output .= '
	hello,guest
'; 
 }  
 $__output .= '

<br />

'; 
for( $i=0; $i< 5;$i++ ){  
 $__output .= '
	'; 
  $__r =$i;  $__output .=  htmlspecialchars($__r);  
 $__output .= ',
'; 
 }  
 $__output .= '

<br />

'; 
$i=0; 
 $__output .= '

'; 
while($i<8){  
 $__output .= '
	'; 
  $__r =$i++;  $__output .=  htmlspecialchars($__r);  
 $__output .= ' ,
'; 
 }  
 $__output .= '

<br />
the tag '; 
 $__output .=   '@'; 
 $__output .= 'end do\'not support '; 
 $__output .=   '@'; 
 $__output .= 'foreach and '; 
 $__output .=   '@'; 
 $__output .= 'section
<br />
'; 
 $__output .= $this->footer();  
 $__output .= '
'; 
 return $__output; 
} 
public function footer(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '
copyright (c) wudimei.com
'; 
 return $__output; 
} 

}