<?php 
class wudimei_view_default_index_function 
{
 public $__vars; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '

first name: '; 
  $__output .=   substr($name,0,4);   
 $__output .= '  <br />
last name: '; 
  $__output .=   substr( $name , strpos( $name,'Qing' ) );   
 $__output .= '  <br />
'; 
  $__output .=   hello("Yang Qing-rong");   
 $__output .= '
'; 
 return $__output; 
} 

}