<?php 
class wudimei_view_default_index_include 
{
 public $__vars; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '<html>
<head>
</head>
<body>
'; 
$__output .= \Wudimei\View::make("default.index.inc_head",$this->__vars );  
 $__output .= '

<div>
'; 
  $__r =$username;  $__output .=  htmlspecialchars($__r);  
 $__output .= '
</div>
</body>
</html>


'; 
 return $__output; 
} 

}