<?php 
class wudimei_view_default_index_php 
{
 public $__vars; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 

   $myTitle = "title";
   
   function add( $a , $b ){
     return $a+$b;
   }
; 
 $__output .= '

'; 
  $__r =$myTitle;  $__output .=  htmlspecialchars($__r);  
 $__output .= '

'; 
  $__r =  add(100,200)  ;  $__output .=  htmlspecialchars($__r);  
 
 return $__output; 
} 

}