<?php 
 require_once \Wudimei\View::$compiled . '/default/layout/main.view.phtml'; 
class wudimei_view_default_index_test  extends wudimei_view_default_layout_main
{
 public $__vars; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function title(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= 'WudimeiPHP View'; 
 return $__output; 
} 
public function content(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '

 	plain_text1 hello,\'world\'. \'\'\' """""
	
	
	
	'; 
  $__output .=   substr($name,0);   
 $__output .= '
	
	'; 
foreach ( $data as $item ):  
 $__output .= '
	  '; 
  $__r =$item['name'];  $__output .=  htmlspecialchars($__r);  
 $__output .= ' 
	'; 
  endforeach;   
 $__output .= '
	
	'; 
if( (  $name == 'yqr' )           ):  
 $__output .= 'dd
	hello
	'; 
elseif ( $name == 'zsf' ):  
 $__output .= 'zsf
	'; 
 else:   
 $__output .= '
	fuck
	
	'; 
  endif;  
 $__output .= '
	a
	'; 
  $__r =$name.$age;  $__output .=  htmlspecialchars($__r);  
 $__output .= 'b
	'; 
  $__r =$name2['first_name']; $__output .=  $__r;  
 $__output .= 'c
	 
	 efg
	 '; 
if( $name == 'yqr' ):  
 $__output .= 'hello'; 
 else:   
 $__output .= 'fuck'; 
  endif;  
 $__output .= '
	 dd
'; 
 
 return $__output; 
} 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 
 $__output .= '

'; 
 $__output .= $this->title();  
 $__output .= '

'; 
 $__output .= $this->content();  
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 $__output .= '
'; 
 return parent::__main__(); 
} 

}