<?php 
 require_once \Wudimei\View::$compiled . '/default/layout/main.view.phtml'; 
class wudimei_view_default_index_test2  extends wudimei_view_default_layout_main
{
 public $__vars; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function title(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= 'WudimeiPHP View2'; 
 return $__output; 
} 
public function content(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '
test2

'; 
 
 return $__output; 
} 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 
 $__output .= '

'; 
 $__output .= $this->title();  
 $__output .= '

'; 
 $__output .= $this->content();  
 
 $__output .= '
'; 
 return parent::__main__(); 
} 

}