<?php 
class wudimei_view_default_index_view_escaped_character 
{
 public $__vars; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .=   '{'; 
 $__output .= '{$name}}
'; 
 $__output .=   '{'; 
 $__output .= '{$name}}
admin'; 
 $__output .=   '@'; 
 $__output .= 'wudimei.com

'; 
 return $__output; 
} 

}