
<!--@if( $role == 'admin')-->
hello,{{$role}}
<!-- @else -->
hello,guest
<!-- @endif -->

<!-- @foreach($years as $year) -->
<!-- {{$year}} --><br />
<!-- @foreachelse -->
sorry,years arrary is empty
<!-- @endforeach -->

@if( count( $years) == 4 )
4 years
@else
not 4 years
@endif

<!-- @section('body') -->
this is the body
<!-- @endsection -->

<!-- this is html comment,was regnized by Wudimei::Parser2 -->


<!--[if lt IE 9]>

      <script src="/{{$role}}/assets/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="/assets/libs/respond/1.4.2/respond.min.js"></script>
<![endif]-->
