
<table border="1">
	<tr>
    	<td>name</td>
    	<td>age</td>
    </tr>
    
@for( $i=0; $i< count( $students );$i++)
    <tr>
    	<td>{{$students[$i]['name']}}</td>
    	<td>{{$students[$i]['age']}}</td>
    </tr>
@endfor

</table>

<br /> <br />

<table border="1">
	<tr>
    	<td>name</td>
    	<td>age</td>
    </tr>
    
@for( $i=0; $i< count( $students );$i++)
    @php($stu = $students[$i];)
    <tr>
    	<td>{{$stu['name']}}</td>
    	<td>{{$stu['age']}}</td>
    </tr>
@endfor

</table>

