<?php 
class wudimei_view_default_layout_main 
{
 public $__vars; 
 public $__view; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '<!DOCTYPE html>
<html>
<head>
<title>'; 
 $__output .= $this->title();  
 $__output .= '</title>
</head>
<body>

<header>this is header</header>
'; 
 $__output .= $this->content();  
 $__output .= '

<footer>this is footer </footer>
</body>
</html>'; 
 return $__output; 
} 
public function title(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= 'WudimeiPHP'; 
 return $__output; 
} 
public function content(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '
default content
'; 
 return $__output; 
} 

}