<?php 
class wudimei_view_default_index_var 
{
 public $__vars; 
 public $__view; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= 'name: '; 
  $__r =$name;  $__output .=  htmlspecialchars($__r);  
 $__output .= ' <br />
site: '; 
  $__r =$site;  $__output .=  htmlspecialchars($__r);  
 $__output .= ' <br />
link: '; 
  $__r =$link;  $__output .=  htmlspecialchars($__r);  
 $__output .= ' <br /> <br />

name: '; 
  $__r =$name; $__output .=  $__r;  
 $__output .= ' <br />
site: '; 
  $__r =$site; $__output .=  $__r;  
 $__output .= ' <br />
link: '; 
  $__r =$link; $__output .=  $__r;  
 $__output .= ' <br /> '; 
 return $__output; 
} 

}