<?php 
class wudimei_view_default_index_while 
{
 public $__vars; 
 public $__view; 
 public function __construct( $vars ) { 
    $this->__vars = $vars; 
 } 
public function __main__(){ 
 $__output = ""; 
 extract( $this->__vars ); 
 $__output .= '
'; 
while( $index < 10 ){  
 $__output .= '
  '; 
  $__r =$index;  $__output .=  htmlspecialchars($__r);  
 $__output .= ' <br />
  '; 
$index++; 
 $__output .= '
'; 
  }   
 $__output .= '

'; 
 return $__output; 
} 

}